### ISSUE TITLE
Collins English Dictionary (汉化版) 查动词短语的时候会自动去掉中间的空格

### ISSUE THREAD

**Issue by funnybones2015** [revir/dictionaries#16]
比如查 give off 会跳转到 giveoff，导致查不到。查 check out，会跳转到checkout的结果。

**Comment by revir** [comment]
多谢， 这个问题新版本已修复。还发现不同的词典在处理词组查询的时候搜索方式是不一样的， 不仅仅是 collins， 朗文， 牛津词典也有这样的问题，一并都修复了。再次感谢！
