### ISSUE TITLE
Feature Implementation: Klingon

### ISSUE THREAD

**Issue by chrispinkney** [revir/dictionaries#20]
Hey there,

Found this on Reddit and tried it out. Nice work! 

Had a silly idea to add Klingon as a dictionary translation. I can try this out and send a PR asap if you're okay with it.

what do you think?

**Comment by revir** [comment]
Cool, couldn't be better :)

**Comment by chrispinkney** [comment]
See #23 😆

**Comment by chrispinkney** [comment]
Closed in #23

**Comment by revir** [comment]
@chrispinkney  I have changed a little bit of your css code, to better fit the small dict window, you will see it. Hope you don't mind.

**Comment by chrispinkney** [comment]
Of course I don't mind, thank you for letting me know!

I'll take a look as soon as I can. Sorry if I made a mistake, my web html/css isn't great.

**Comment by revir** [comment]
Thanks bro, you are too humble.
