### ISSUE TITLE
建议增加最大规模的权威在线免费俚语词典 Green Dictionary of Slang （https://greensdictofslang.com）

### ISSUE THREAD

**Issue by funnybones2015** [revir/dictionaries#4]
Green Dictionary of Slang 是目前权威版权词典里面规模最大的一本俚语词典，而且现在其官网https://greensdictofslang.com 已经变成完全免费，以前其中的例句是收费的。该词典的俚语收词范围很大，而且包括各种英文国家的丰富例句，十分值得收录。由于是版权词典，比 Urban dictionary 这种自由开放的词典更加严谨权威。非常多俚语的用法只能在该词典查到。
![ED0JQm8M5f](https://user-images.githubusercontent.com/15063728/81476324-00f97000-9244-11ea-9bd4-c605bfa85366.png)

比如前几天在网上看到一个句子，用到了dumb，在那个句子里是表示强调的意思。而这个意思在其他很多词典里都找不到这个解释。只能在green dictionary of slang 里查到。

**Comment by revir** [comment]
Thanks for recommend this dictionary, I add it to the list, just wait for reviewing in the webstore.

**Comment by funnybones2015** [comment]
really grateful for your quick action and kindness!!
