### ISSUE TITLE
能否添加Wiktionary移动网页版？

### ISSUE THREAD

**Issue by funnybones2015** [revir/dictionaries#5]
Wiktionary 是一个不可多得的网络开放大型综合型词典，收词量非常全面，而且根据我多年的查词经验，很多专科领域的词义和新词新义只有这本词典有所收录。相对于Oxford、Webster等传统词典，可以形成良好的补充。强烈建议加入~~~   它的移动网页版比标准网页版更加清爽易读，没有多余的东西。

移动网页版主页：https://en.m.wiktionary.org/wiki/Wiktionary:Main_Page

**Comment by revir** [comment]
Added on next version

**Comment by funnybones2015** [comment]
感谢感谢！！！
