### ISSUE TITLE
Wordreference上的英汉词典也很独到，建议加入，请见文内的评测文章

### ISSUE THREAD

**Issue by funnybones2015** [revir/dictionaries#6]
Wordreference上的英汉词典给的译文比较准确，释义也比较全面，有很多是其他英汉词典少有的，也十分值得收进来，建议考虑一下~~

相关介绍文章如下：
https://www.pdawiki.com/forum/forum.php?mod=viewthread&tid=18172&highlight=WordReference

**Comment by revir** [comment]
Added on next version

**Comment by funnybones2015** [comment]
thank you so much!!!

**Comment by funnybones2015** [comment]
好像新版加的wordreference是英文版的，而不是英汉版的。
