### ISSUE TITLE
再推荐几本好用的词典

### ISSUE THREAD

**Issue by funnybones2015** [revir/dictionaries#7]
1. 韦氏高阶词典（不可多得的美式英语高阶学习型词典）：https://learnersdictionary.com/
2. 柯林斯在线词典汉化版（相比现有内置的柯林斯英语在线词典，界面汉化，更方便查询，而且还包含一些英汉的译文）：https://www.collinsdictionary.com/zh/
3. 剑桥英汉词典在线版（目前全网唯一的高阶英汉学习型词典在线版，译文相比纸版也有不少更新，比如 viral 的第二个新词义和双语例句是纸本没有的）：https://dictionary.cambridge.org/zhs/

![image](https://user-images.githubusercontent.com/15063728/82191572-4ba27880-9925-11ea-9af2-d3e6e4f5da18.png)

**Comment by revir** [comment]
added in next version

**Comment by funnybones2015** [comment]
非常感谢，开发者辛苦！！！

**Comment by funnybones2015** [comment]
新版好像没有添加韦氏高阶学习词典 https://learnersdictionary.com/
